/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jogoforca;

import java.awt.FlowLayout;
import java.awt.Font;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Willyan
 */
public class NewJFrame extends javax.swing.JFrame {
    
    private String palavra;
    private char letras[];
    private char letrasJogadas[];
    int jogadas = 0;
    private int tamanho;
    private int numErros;
    private final int MAX_ERROS = 5;
    private int numAcertos;
    private JButton botoesLetras[];
     
            
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        lerPalavra();
        iniciarVariaveis();
        iniciarBotoes();
        this.pack();
        
    }
    
    private void lerPalavra(){
        this.palavra = JOptionPane.showInputDialog("Digite uma palavra:");
        this.tamanho = palavra.length(); 
    }
    
    private void iniciarVariaveis(){
        this.numErros = 0;
        this.numAcertos = 0;
        this.letras = palavra.toCharArray();        // converter a string para array de char
        this.botoesLetras = new JButton[tamanho];   // aloca o vetor de botoes
    }
    
    private void iniciarBotoes(){
        painelPalavra.setLayout(new FlowLayout());
        Font aux = new Font("Arial", Font.PLAIN, 70);
        
        for (int i=0; i<tamanho; i++){
            botoesLetras[i] = new JButton("  ");
            botoesLetras[i].setFont(aux);
            botoesLetras[i].setEnabled(false);
            painelPalavra.add(botoesLetras[i]);
        }
    }
    
    private void verificarLetra() {
        char visor[] = Letra.getText().toCharArray();
        
        if (jogadas == 0) {
            letrasJogadas = new char[1];
            letrasJogadas[0] = visor[0];
            jogadas++;
        } else {
            for (int i=1; i<jogadas; i++) {
                if (visor[0] == letrasJogadas[i]) {
                    JOptionPane.showMessageDialog(painelPalavra, "Letra já jogada!");
                    return;
                }
            }
            letrasJogadas = push(letrasJogadas, visor[0]);
            jogadas++;
        }
        
        int contadorAcertos = 0;
        
        for (int i=0; i<tamanho; i++) {
            if(visor[0] == letras[i]) {
                botoesLetras[i].setText(letras[i] + "");
                this.numAcertos++;
                contadorAcertos++;
                this.pack();
            }
        }
        
        if (contadorAcertos == 0) {
            marcarErro(visor[0]);
        }
        
        if (this.numErros > MAX_ERROS) {
            JOptionPane.showMessageDialog(this, "Limite de erros, PERDEU! \n A palavra era: " + palavra);
            System.exit(0);
        } else if (this.numAcertos == tamanho) {
            JOptionPane.showMessageDialog(this, "Você GANHOU!");
            System.exit(0);
        }
    }
    
    private void marcarErro(char letraErro) {
        this.numErros++;
        Erros.setText(Erros.getText() + letraErro + " ");
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelLetra = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Letra = new javax.swing.JTextPane();
        botaoPalpite = new javax.swing.JButton();
        painelPalavra = new javax.swing.JPanel();
        Erros = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PainelLetra.setBorder(javax.swing.BorderFactory.createTitledBorder("Letra"));
        PainelLetra.setLayout(new java.awt.GridLayout(1, 0, 10, 10));

        jScrollPane1.setViewportView(Letra);

        PainelLetra.add(jScrollPane1);

        botaoPalpite.setText("Palpite");
        botaoPalpite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPalpiteActionPerformed(evt);
            }
        });
        PainelLetra.add(botaoPalpite);

        painelPalavra.setBorder(javax.swing.BorderFactory.createTitledBorder("Palavra"));
        painelPalavra.setToolTipText("");
        painelPalavra.setName(""); // NOI18N

        javax.swing.GroupLayout painelPalavraLayout = new javax.swing.GroupLayout(painelPalavra);
        painelPalavra.setLayout(painelPalavraLayout);
        painelPalavraLayout.setHorizontalGroup(
            painelPalavraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        painelPalavraLayout.setVerticalGroup(
            painelPalavraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 98, Short.MAX_VALUE)
        );

        Erros.setBorder(javax.swing.BorderFactory.createTitledBorder("Erros:"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelPalavra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PainelLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Erros, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelPalavra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PainelLetra, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(Erros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoPalpiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPalpiteActionPerformed
        verificarLetra();
    }//GEN-LAST:event_botaoPalpiteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            };
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Erros;
    private javax.swing.JTextPane Letra;
    private javax.swing.JPanel PainelLetra;
    private javax.swing.JButton botaoPalpite;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel painelPalavra;
    // End of variables declaration//GEN-END:variables

    private char[] push(char[] array, char push) {
        char[] longer = new char[array.length + 1];
        System.arraycopy(array, 0, longer, 0, array.length);
        longer[array.length] = push;
        return longer;
    }
}
